### ISSUE TITLE
Support for `--reaches` option

### ISSUE THREAD

**Issue by katz** [MH4GF/dependency-cruiser-report-action#331]
Hi,

Thank you for the great GitHub Action!

I tried to leverage this action in our project and found that there is another way to visualize dependencies.
Currently, this action uses the `--focus` option, which displays the dependencies/dependents of the files passed to the option. Although it's useful, the main purpose of the visualization is to identify which files are dependents of the files changed in a Pull Request. If the action uses the `--reaches` option, it can visualize which modules will be directly or indirectly affected by a change in a Pull Request.

For example, in Pull Request #306, the action runs the following command:

```bash
pnpm exec depcruise  \
  --output-type mermaid  \
  --config .dependency-cruiser.js  \
  --focus "^dist/index.js|^src/options.ts|^src/options/filterSupportedFiles.test.ts|^src/options/formatFocusOption.test.ts|^src/options/validateOptions.test.ts|^src/options/validateOptions.ts|^src/report/body/reportBody.test.ts|^src/report/body/uniqueTag.test.ts|^src/report/fetchPreviousReport.ts|^test/runDepcruise/index.test.ts|^test/runDepcruise/sample/__mocks__/test/fixtures/cjs/root_one.js|^test/runDepcruise/sample/__mocks__/test/fixtures/cjs/root_two.js"  \
  dist/index.js src/options.ts src/options/filterSupportedFiles.test.ts src/options/formatFocusOption.test.ts src/options/validateOptions.test.ts src/options/validateOptions.ts src/report/body/reportBody.test.ts src/report/body/uniqueTag.test.ts src/report/fetchPreviousReport.ts test/runDepcruise/index.test.ts test/runDepcruise/sample/__mocks__/test/fixtures/cjs/root_one.js test/runDepcruise/sample/__mocks__/test/fixtures/cjs/root_two.js
```

The output only visualizes the dependencies of the changed files.

```mermaid
flowchart LR

subgraph 0["src"]
1["options.ts"]
subgraph 2["options"]
3["filterSupportedFiles.ts"]
4["formatFocusOption.ts"]
5["getConfigFilePath.ts"]
6["validateOptions.ts"]
8["filterSupportedFiles.test.ts"]
9["formatFocusOption.test.ts"]
A["validateOptions.test.ts"]
end
7["ActionError.ts"]
subgraph B["report"]
subgraph C["body"]
D["reportBody.test.ts"]
E["reportBody.ts"]
F["uniqueTag.ts"]
G["uniqueTag.test.ts"]
end
H["fetchPreviousReport.ts"]
end
I["type.ts"]
end
1-->3
1-->4
1-->5
1-->6
1-->6
6-->7
8-->3
9-->4
A-->7
A-->6
A-->6
D-->E
E-->F
G-->F
H-->1
H-->I
H-->F

style 1 fill:lime,color:black
style 6 fill:lime,color:black
style 8 fill:lime,color:black
style 9 fill:lime,color:black
style A fill:lime,color:black
style D fill:lime,color:black
style G fill:lime,color:black
style H fill:lime,color:black
```

On the other hand, if I run the command with the `--reaches` option, it can visualize which modules will be directly or indirectly affected by a change:

```bash
pnpm exec depcruise  \
  --output-type mermaid  \
  --config .dependency-cruiser.js  \
  --max-depth 2 \
  --reaches "^dist/index.js|^src/options.ts|^src/options/filterSupportedFiles.test.ts|^src/options/formatFocusOption.test.ts|^src/options/validateOptions.test.ts|^src/options/validateOptions.ts|^src/report/body/reportBody.test.ts|^src/report/body/uniqueTag.test.ts|^src/report/fetchPreviousReport.ts|^test/runDepcruise/index.test.ts|^test/runDepcruise/sample/__mocks__/test/fixtures/cjs/root_one.js|^test/runDepcruise/sample/__mocks__/test/fixtures/cjs/root_two.js" \
  src
```

```mermaid
flowchart LR

subgraph 0["src"]
1["installDependencies.ts"]
2["options.ts"]
subgraph 3["options"]
4["validateOptions.ts"]
9["filterSupportedFiles.test.ts"]
A["formatFocusOption.test.ts"]
B["validateOptions.test.ts"]
end
5["main.ts"]
subgraph 6["report"]
7["generateReport.ts"]
8["fetchPreviousReport.ts"]
subgraph C["body"]
D["reportBody.test.ts"]
E["uniqueTag.test.ts"]
end
end
end
1-->2
2-->4
2-->4
5-->1
5-->2
5-->7
7-->2
7-->8
B-->4
B-->4

style 2 fill:lime,color:black
style 4 fill:lime,color:black
style 8 fill:lime,color:black
style 9 fill:lime,color:black
style A fill:lime,color:black
style B fill:lime,color:black
style D fill:lime,color:black
style E fill:lime,color:black
```

**Comment by MH4GF** [comment]
@katz Thanks for the comment 😄 
Very nice! Since the purpose of this action is to visualize the scope of changes affected, the `--reaches` option may be optimal.
It would be nice to be able to choose between `--focus` and `--reaches` in the action input.

If you don't mind, could you try to submit a PR?

**Comment by katz** [comment]
@MH4GF Hi, thanks for your input!
Let me try to prepare a PR to support `--reaches` option. But, it may take several months....

**Comment by MH4GF** [comment]
@katz Hey, I've pushed the prerelease version, can you try it?
https://github.com/MH4GF/dependency-cruiser-report-action/releases/tag/v2.5.0-0

```yaml
    steps:
      - uses: MH4GF/dependency-cruiser-report-action@v2.5.0-0
        with:
          visualize-type: reaches
```

One difference from the existing system is that the only file to be scanned is the file that has been changed, but when reaches are set, the file is changed to `.`. example: 

- focus: https://github.com/MH4GF/dependency-cruiser-report-action/pull/338#issuecomment-2041667114
- reaches: https://github.com/MH4GF/dependency-cruiser-report-action/pull/338#issuecomment-2041674289

This is necessary to include transitive modules in the output, but I'm not sure if it's appropriate to do so in a custom action. I would like to be sure that this meets your use case!
